version: 1
dataset:
 name: house-prices-advanced-regression-techniques
 type: competition
 download-command: kaggle competitions download
 data-directory-path: /home/satyapati/WorkSpace/Learning/Housing_price/data/raw
 steps:
  - download
  - unzip
  - remove-zip
