version: 1
dataset:
 name: house-prices-advanced-regression-techniques
 type: competition
 download-command: kaggle competitions download
 raw_data_path: /home/satyapati/WorkSpace/Learning/Housing_price/data/raw
 train_file: train.csv
 test_file: test.csv
 metadata_path: /home/satyapati/WorkSpace/Learning/Housing_price/data/meta
 processed_data_path: /home/satyapati/WorkSpace/Learning/Housing_price/data/processed
 steps:
  - download
  - unzip
  - remove-zip
